# Generated by Django 3.2.9 on 2021-11-09 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211110_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
