# Generated by Django 3.2.9 on 2021-11-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='slug',
            new_name='sluged',
        ),
    ]
