# Generated by Django 3.2.9 on 2021-11-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_rename_slug_article_sluged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sluged',
            field=models.SlugField(default=models.CharField(max_length=100)),
        ),
    ]
