# Generated by Django 3.2.9 on 2021-11-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_article_sluged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sluged',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
    ]
