# Generated by Django 3.2.9 on 2021-11-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_article_sluged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='sluged',
            new_name='slug',
        ),
    ]
